version: '3.9'

networks:
  app_network:

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dvigus_db
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app_network